[FEAT] 게임방법 화면 뷰#28
CapstoneDesign-2022/FindDict-Client pull request #39
Opened 2022-11-04 12:09 UTC by separk314

## 작업한 내용
- 게임방법 화면 뷰 CollectionView로 작업

## PR Point
- 게임방법 내용은 넣어두었고 사진은 나중에 어플 완성되면 그때 캡쳐해서 넣겠습니당
- offset 반대 == inset이라고 생각해서 inset(음수값) == offset(양수값)이 성립하는줄 알았는데 구글링해보니 개념이 살짝 다른 것 같아요. offset은 element와의 간격에 사용하고, inset은 superview와의 간격에 사용한다고 합니다. 
예를 들어서 childView가 superView에서 50씩 떨어지게 만들 때는 offset을 사용하면 top, bottom, left, right에 각각 50, -50, 50, -50을 주는데 inset을 사용하면 50, 50, 50, 50을 준다고 해요.
- frame은 superview 좌표시스템 안에서 view의 위치와 크기, bounds는 자신만의 좌표시스템 안에서 위치와 크기를 나타낸다고 합니다. UIView의 height와 width를 설정할 때 frame으로 조절해보려 했는데 잘 안 되어서 스냅킷을 사용했습니다.
- 색상이랑 그림자 주는 메서드 등이 디벨롭 브랜치에 있어서 머지 후에 색상과 그림자 적용하겠습니다

## 📸 스크린샷
https://user-images.githubusercontent.com/71963320/199969182-a732bbf7-f793-43cd-85a0-b1fcf9d8fe14.mp4

## 관련 이슈
- Resolved: #28

2022-11-04 13:05 UTC, jimin-kiim requested changes
너무너무 수고하셨습니다ㅜㅜ🥺👍🏻
'게임 설명'레이블 & 홈으로의 이동 버튼은 고정시켜두고 셀만 전환될 수 있게만 수정해주시면 될 것 같네요😄 홈 버튼 클릭 시 홈으로 이동하는 기능도 되어 있는 건지 다시 확인차 여쭤봅니당!!

2022-11-04 13:05 UTC, jimin-kiim commented on FindDict/FindDict/Global/Extensions/UICollectionViewCell+.swift
> +extension UICollectionViewCell: Reusable { }
안 쓰게 된 파일이라 지워주셔도 될 것 같네요😄

2022-11-04 13:05 UTC, jimin-kiim commented on FindDict/FindDict/Global/Extensions/UIViewController+.swift
> +import SwiftUI
swiftUI는 쓰지 않을 거라 지워주셔도 될 것 같습니다!

2022-11-04 13:05 UTC, jimin-kiim commented on FindDict/FindDict/Global/Extensions/UIViewController+.swift
> +    private struct Preview: UIViewControllerRepresentable {
해당 코드는 시뮬레이터를 사용하지 않고 xcode 화면 내에서 SwiftUI의 '프리뷰'라는 기능을 통해 미리보기를 할 때 사용되는 코드입니다! 따라서 삭제해주셔도 될 것 같습니당ㅎㅎ

2022-11-04 13:05 UTC, jimin-kiim commented on FindDict/FindDict/Protocols/Reusable.swift
> +import Foundation
여기 파일도 삭제해주셔도 될 것 같습니당!

2022-11-04 13:05 UTC, jimin-kiim commented on FindDict/FindDict/Sources/Tutorial/GameTutorialCVC.swift
> +    lazy var pageButton = UIButton().then{
해당 버튼은 사용되지 않는 버튼이 맞을까요?

2022-11-04 13:05 UTC, jimin-kiim commented on FindDict/FindDict/Sources/Tutorial/GameTutorialVC.swift
> +    private lazy var increasedDataSource: [GameTutorialCVCModel] = {
마지막 셀이 나왔을 시 다시 처음 셀로 가길 원하신 건가요? 그렇지 않다면 increasedDataSource는 삭제해주셔도 될 것 같다고 생각했는데 의도를 먼저 여쭤보는 게 맞을 것 같네용ㅎㅎ!

2022-11-09 06:54 UTC, separk314 commented on FindDict/FindDict/Sources/Tutorial/GameTutorialCVC.swift
> +    lazy var pageButton = UIButton().then{
이 코드에서 사용하지는 않았는데 페이지 끄트머리에 넣겠습니다!!

2022-11-09 06:55 UTC, separk314 commented on FindDict/FindDict/Sources/Tutorial/GameTutorialVC.swift
> +    private lazy var increasedDataSource: [GameTutorialCVCModel] = {
ㅎㅎ,,없애겠슴다

2022-11-10 07:55 UTC, jimin-kiim approved these changes
수고하셨습니다!

2022-11-10 08:03 UTC, kkl4846 approved these changes

2022-11-10 08:08 UTC, merged